
name: Test EFS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: |
          git clone https://github.com/aws/efs-utils || /bin/true
          cd efs-utils
          ./build-deb.sh
          sudo apt-get -y install ./build/amazon-efs-utils*deb
      - run: sudo mkdir -p '~/.m2'
